development:
  db: 0
  host: localhost
  port: 6379
  namespace: healthcan_dev
  redis: redis://localhost:6379/0/healthcan_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: healthcan_test
  redis: redis://localhost:6379/1/healthcan_test
production:
  db: 0
  host: localhost
  port: 6379
  namespace: healthcan_prod
  redis: redis://localhost:6379/0/healthcan_prod
